# Force refresh
name: Update Stock Market Dataset

on:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12:00 UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch Stock Data
        run: |
          python scripts/fetch_all_stocks.py

      - name: Commit & Push Updated Data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/stocks.json
          git commit -m "Updated stock data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
