name: Auto Trade Based on GPT

on:
  workflow_run:
    workflows: ["Rank Stocks with GPT"]
    types:
      - completed
  workflow_dispatch:

jobs:
  auto-trade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Auto Trader
        env:
          BROKER_KEY: ${{ secrets.BROKER_KEY }}
          BROKER_SECRET: ${{ secrets.BROKER_SECRET }}
        run: |
          python scripts/auto_trade.py
