name: Auto Trade with Alpaca

on:
  workflow_run:
    workflows: ["Rank Stocks with GPT"]
    types:
      - completed

jobs:
  auto-trade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run auto-trader
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}
          ALPACA_ENDPOINT: ${{ secrets.ALPACA_ENDPOINT }}
        run: |
          python scripts/alpaca_trader.py
