name: Rank and Trade

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ✅ Force stocks.json to refresh from Polygon
      - name: Update stock universe from Polygon
        run: python scripts/update_universe.py
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

      - name: Verify stocks.json exists
        run: |
          if [ ! -s data/stocks.json ]; then
            echo "stocks.json is missing or empty!"
            exit 1
          fi

      - name: Update crypto universe
        run: python scripts/update_universe_crypto.py

      - name: Rank stocks & crypto using GPT
        run: python scripts/gpt_rank_stocks.py --top 50
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # ✅ Merge GPT + Whale recommendations
      - name: Merge recommendations
        run: python scripts/merge_recommendations.py

      - name: Execute trading logic
        run: python scripts/auto_trade.py
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          # 👇 fallback in case your repo uses ALPACA_API_SECRET instead of ALPACA_SECRET_KEY
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY || secrets.ALPACA_API_SECRET }}
          RECS_FILE: data/merged_recommendations.json
