name: Rank and Trade

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * *"  # Runs after update_universe

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Rank stocks using GPT
        run: |
          echo "Ranking stocks..."
          python scripts/gpt_rank_stock.py --input data/stocks.json --top 20

      - name: Execute trading logic
        run: |
          echo "Executing trades..."
          python scripts/auto_trade.py --mode paper
