name: Rank and Trade

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug available files
        run: |
          echo "=== Listing scripts directory ==="
          ls -R scripts/

      - name: Update stock universe (Polygon)
        run: python scripts/update_universe.py
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

      - name: Show stocks.json content
        run: |
          echo "=== First 20 lines of stocks.json ==="
          head -n 20 data/stocks.json || echo "stocks.json not found"

      - name: Update crypto universe
        run: python scripts/update_universe_crypto.py

      - name: Rank stocks & crypto
        run: python scripts/gpt_rank_stocks.py

      - name: Execute trading logic
        run: python scripts/auto_trade.py
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
