name: Rank & Paper Trade
on:
  workflow_dispatch:
  schedule:
    - cron: "30 14 * * 1-5"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Rank (GPT or heuristic)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/gpt_rank_stocks.py --input data/stocks.json --top 20
      - name: Paper trade via Alpaca
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          ALPACA_BASE_URL: "https://paper-api.alpaca.markets"
          DRY_RUN: "false"
          MAX_PORTFOLIO_SIZE: "5"
          MAX_POSITION_USD: "1000"
          MIN_CONFIDENCE: "0.7"
          EXIT_BELOW_CONFIDENCE: "0.5"
          STOP_LOSS_PCT: "0.05"
          TAKE_PROFIT_PCT: "0.1"
        run: |
          python -m scripts.auto_trade
