name: Rank and Trade

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update stock universe from Polygon
        run: python scripts/update_universe.py
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

      - name: Update crypto universe
        run: python scripts/update_universe_crypto.py

      - name: Rank stocks & crypto using GPT
        run: python scripts/gpt_rank_stocks.py

      - name: Execute trading logic
        run: python scripts/auto_trade.py
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
