name: Update Stock Market Dataset

on:
  schedule:
    - cron: '0 22 * * *' # Runs daily at 10 PM UTC (~5 PM EST)
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Send trigger request to Render
      run: |
        echo "Triggering MarketBot API..."
        curl -X GET "https://marketbot-ctai.onrender.com/export/all?async=1"

    - name: Wait for data build
      run: sleep 120

    - name: Confirm status
      run: |
        curl "https://marketbot-ctai.onrender.com/status"
