name: Update Stock Market Dataset

on:
  schedule:
    - cron: "0 12 * * 1-5" # Runs every weekday at 12:00 UTC
  workflow_dispatch: # Allows manual runs

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # REQUIRED to allow pushes
      id-token: write

    steps:
      # ----------------------------
      # 1. Checkout Repository
      # ----------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ----------------------------
      # 2. Set Up Python
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # ----------------------------
      # 3. Install Dependencies
      # ----------------------------
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lxml pandas requests beautifulsoup4 openai

      # ----------------------------
      # 4. Fetch Stock Data
      # ----------------------------
      - name: Fetch Stock Data
        run: |
          python scripts/fetch_all_stocks.py

      # ----------------------------
      # 5. Commit & Push Updated Data
      # ----------------------------
      - name: Commit & Push Updated Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/stocks.json
          git commit -m "Updated stock data $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

      # ----------------------------
      # 6. (OPTIONAL) GPT Analysis Hook
      # ----------------------------
      - name: GPT Stock Analysis
        if: always()
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Running GPT stock ranking..."
          python scripts/gpt_rank_stocks.py || echo "Skipping GPT for now"
