name: Update Universe

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      FMP_API_KEY: ${{ secrets.FMP_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Fetch S&P 500 stocks from FMP API
      - name: Update stock universe
        run: |
          echo "Fetching S&P 500 stocks..."
          curl -s "https://financialmodelingprep.com/api/v3/sp500_constituent?apikey=${FMP_API_KEY}" \
            | jq '.' > data/stocks.json

      # Fetch top crypto coins from CoinGecko API
      - name: Update crypto universe
        run: |
          echo "Fetching top crypto assets..."
          curl -s "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=50&page=1&sparkline=false" \
            | jq '.' > data/crypto.json

      - name: Commit dataset
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/stocks.json data/crypto.json
          git commit -m "Updated stocks + crypto data" || echo "No changes to commit"
          git push
