name: Update Universe

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update stock universe via Polygon
        run: |
          echo "🚀 Fetching stock universe..."
          python scripts/update_universe.py

      - name: Rank stocks
        run: |
          echo "🏆 Ranking top stocks..."
          python scripts/gpt_rank_stocks.py --top 20

      - name: Commit updated datasets
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/stocks.json
          git commit -m "Updated stock dataset [skip ci]" || echo "No changes to commit"
          git push origin main
